line-length = 100
target-version = "py313"

[lint]
select = [
  "E",
  "F",
  "I",
  "N",
  "UP",
  "ASYNC",
]
ignore = [
  "ANN101",
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
